server:
  port: 8080

spring:
  application:
    name: fleet-management
  
  profiles:
    active: local

  # R2DBC (Application Runtime)
  # ✅ CORRECTION: Utiliser yowyob_db au lieu de yowyob
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password
    pool:
      enabled: true
      initial-size: 2
      max-size: 10
      validation-query: "SELECT 1"
      max-idle-time: 10m

  # JDBC (Liquibase Migration)
  datasource:
    url: jdbc:postgresql://localhost:5432/yowyob_db
    username: fleet_admin
    password: fleet_password
    driver-class-name: org.postgresql.Driver

  # LIQUIBASE
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml
    default-schema: public
    liquibase-schema: public
    enabled: true
    contexts: local

  # REDIS
  data:
    redis:
      host: localhost
      port: 6379
      password: ""

  # KAFKA
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: fleet-management-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

  docker:
    compose:
      enabled: false

# CONFIG METIER
application:
  external:
    vehicle-service-url:  https://vehicule-service.pynfi.com
    geofence-service-url: https://geofence-service.pynfi.com
    # geofence-service-url: http://localhost:8081
    payment-service-url:  https://payment-service.pynfi.com
  auth:
    mode: remote
    url: https://auth-service.pynfi.com

  notification:
    mode: http # 'http' ou 'kafka'
    url: https://notification-service.pynfi.com # URL du Swagger fourni
    service-token: "a77599d3-8de7-4d52-b9d0-2202b2e13a9e" # Token récupéré après enregistrement du service
    templates:
      new-offer: 1        # ID template: Nouvelle offre pour les chauffeurs
      driver-applied: 2   # ID template: Un chauffeur a postulé (pour le client)
      driver-selected: 3  # ID template: Vous avez été choisi (pour le chauffeur)
      ride-confirmed: 4   # ID template: Le chauffeur arrive (pour le client)
      ride-cancelled: 5   # ID template: Course annulée
      admin-validation: 7 # ID template: admin a validé le profil du driver
 
  geofence-system-user:
    username: "fleetmanagementuser"
    password: "system_password_secure" # À changer en prod
    organization-id: "723e4567-e89b-12d3-a456-426614174000" # UUID de notre application dans
 
  bootstrap:
    admin:
      username: "superadmin123"
      email: "superadmin123@transens.com"
      password: "password123" 
      phone: "+23761213141516"
      firstname: "System"
      lastname: "Administrator"
  # Kafka topics
  kafka:
    topics:
      geofence-alerts: geofence-alerts-topic

# MONITORING
management:
  endpoints:
    web:
      exposure:
        include: ["health","info","prometheus"]
  endpoint:
    health:
      show-details: "always"
      probes:
        enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

# Resilience4j
resilience4j:
  circuitbreaker:
    instances: {}